name: 'Lint Mapbox GL Style'
description: 'Lint Mapbox GL Style'
inputs:
  style-paths:
    description: 'Path of styles to lint'
    required: true
outputs:
  lint-message:
    description: 'Lint message'
    value: ${{ steps.run-lint.outputs.lint-message }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - id: install
      name: Install dependencies
      run: npm install github:stamen/mapbox-gl-style-linter#v0.1.3 --global
      shell: bash

    - id: run-lint
      name: Run lint command
      run: |
        export LINTER_OUTPUT="$(mapbox-gl-style-lint ${{ inputs.style-paths }})"
        LINTER_OUTPUT="${LINTER_OUTPUT//'%'/'%25'}"
        LINTER_OUTPUT="${LINTER_OUTPUT//$'\n'/'%0A'}"
        LINTER_OUTPUT="${LINTER_OUTPUT//$'\r'/'%0D'}"
        echo "::set-output name=lint-message::$(echo "$LINTER_OUTPUT")"
      shell: bash

    - id: fail-on-message
      name: Check failure
      run: |
        if [ "${{ steps.run-lint.outputs.lint-message }}" != "" ]
          then exit 1
        fi
      shell: bash
